id: I80E928DB
legacy_id: P000508
ocr_import_info:
  bdrc_scan_id: W2PD17096
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T15:48:27'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T09:43:50.580325+00:00'
last_modified: 2022-09-03 17:44:38.883372
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD17096
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2PD17096
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཡོན་ཏན་མཛོད་ཀྱི་འགྲེལ་པ་ཉི་ཟླའི་སྒྲོན་མེ། རྩྭ་ར་མཁན་པོ་ཆོས་གྲགས་ཀྱི་མཆན་ཅན།
  author: མི་ཉག་རྩ་ར་མཁན་ཆེན་ཐུབ་བསྟན་ཆོས་ཀྱི་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.6559723064172873
  ocr_word_median_confidence_index: 0.699999988079071
quality: null
bases:
  I3PD880:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3PD880
      total_pages: 778
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3PD880.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6682060648796723
    legacy_id: v001
  I3PD881:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3PD881
      total_pages: 638
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3PD881.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6430789309274284
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
